version: "3.9"
services:
  sso:
    build: .
    links:
      - sso-redis
    networks:
      - proxynet
    environment:
      - DOCKER=1
      - REDIS_HOST=sso-redis

  sso-redis:
    image: redis:6.2.6-alpine3.14
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet